import base64
from pathlib import Path
from email.mime.text import MIMEText

from mcp.server.fastmcp import FastMCP
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build


# ============================================================
# MCP SERVER
# ============================================================

mcp = FastMCP("gmail-server")


# ============================================================
# GMAIL CONFIGURATION
# ============================================================

SCOPES = [
    "https://www.googleapis.com/auth/gmail.send"
]


# Get the directory where this file is located
BASE_DIR = Path(__file__).resolve().parent

# token.json generated by gmail_Auth.py
TOKEN_FILE = BASE_DIR / "token.json"


# ============================================================
# CREATE GMAIL SERVICE
# ============================================================

def get_gmail_service():
    """
    Load OAuth credentials from token.json
    and create a Gmail API service.
    """

    # --------------------------------------------------------
    # Check whether token.json exists
    # --------------------------------------------------------

    if not TOKEN_FILE.exists():
        raise FileNotFoundError(
            f"token.json not found at: {TOKEN_FILE}. "
            "Run gmail_Auth.py first."
        )

    # --------------------------------------------------------
    # Load complete OAuth credentials
    #
    # token.json contains:
    # - access token
    # - refresh token
    # - token URI
    # - client ID
    # - client secret
    # --------------------------------------------------------

    credentials = Credentials.from_authorized_user_file(
        str(TOKEN_FILE),
        SCOPES,
    )

    # --------------------------------------------------------
    # Build Gmail API service
    # --------------------------------------------------------

    service = build(
        "gmail",
        "v1",
        credentials=credentials,
    )

    return service


# ============================================================
# SEND EMAIL TOOL
# ============================================================

@mcp.tool()
def send_email(
    to: str,
    subject: str,
    body: str,
) -> dict:
    """
    Send an email through Gmail.
    """

    try:

        # ----------------------------------------------------
        # Get Gmail service
        # ----------------------------------------------------

        gmail = get_gmail_service()

        # ----------------------------------------------------
        # Create MIME email
        # ----------------------------------------------------

        message = MIMEText(
            body,
            "plain",
            "utf-8",
        )

        message["To"] = to
        message["Subject"] = subject

        # ----------------------------------------------------
        # Encode email for Gmail API
        # ----------------------------------------------------

        raw_message = base64.urlsafe_b64encode(
            message.as_bytes()
        ).decode()

        gmail_message = {
            "raw": raw_message
        }

        # ----------------------------------------------------
        # Send email
        # ----------------------------------------------------

        result = (
            gmail.users()
            .messages()
            .send(
                userId="me",
                body=gmail_message,
            )
            .execute()
        )

        # ----------------------------------------------------
        # SUCCESS
        # ----------------------------------------------------

        return {
            "success": True,
            "message": "Email sent successfully",
            "message_id": result.get("id"),
        }

    except Exception as e:

        # ----------------------------------------------------
        # FAILURE
        # ----------------------------------------------------

        return {
            "success": False,
            "message": str(e),
        }


# ============================================================
# START MCP SERVER
# ============================================================

if __name__ == "__main__":

    mcp.run(
        transport="stdio"
    )