[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "blogagentic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "email-validator>=2.3.0",
    "fastapi>=0.115.12",
    "google-api-python-client>=2.199.0",
    "google-auth>=2.56.3",
    "google-auth-oauthlib>=1.4.0",
    "google-genai>=2.19.0",
    "langchain>=0.3.25",
    "langchain-community>=0.3.25",
    "langchain-core>=0.3.65",
    "langchain-groq>=0.3.2",
    "langchain-litellm>=0.7.0",
    "langgraph>=0.4.8",
    "langgraph-checkpoint-postgres>=3.1.2",
    "langgraph-cli[inmem]>=0.3.1",
    "litellm>=1.97.0",
    "mcp>=2.0.0",
    "nemoguardrails>=0.23.0",
    "psycopg[binary]>=3.3.4",
    "streamlit>=1.62.0",
    "uvicorn>=0.34.3",
    "watchdog>=6.0.0",
]

[tool.setuptools.packages.find]
include = ["src*"]
