models:
  - type: main
    engine: nim
    model: meta/llama-3.1-8b-instruct

  - type: content_safety
    engine: nim
    model: nvidia/llama-3.1-nemotron-safety-guard-8b-v3

  - type: topic_control
    engine: nim
    model: nvidia/llama-3.1-nemoguard-8b-topic-control

  - type: jailbreak_detection
    engine: nim
    model: nvidia/nemoguard-jailbreak-detect

rails:
  input:
    parallel: false

    flows:
      - content safety check input $model=content_safety

      - jailbreak detection model

      - topic safety check input $model=topic_control

  output:
    flows:
      - content safety check output $model=content_safety

  config:
    jailbreak_detection:
      nim_base_url: "https://ai.api.nvidia.com"

      nim_server_endpoint: "/v1/security/nvidia/nemoguard-jailbreak-detect"

      api_key_env_var: "NVIDIA_API_KEY"

enable_rails_exceptions: true
