models:
  - type: main
    engine: nim
    model: nvidia/nemotron-3.5-content-safety

enable_rails_exceptions: True

rails:
  input:
    flows:
      - self check input

  output:
    flows:
      - self check output
